M48
; DRILL file {KiCad 8.0.2} date 2024-08-19T18:08:18-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-19T18:08:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X7.903Y-4.2981
X7.903Y-4.5659
T2
X7.279Y-3.519
X7.279Y-5.275
M30
