M48
; DRILL file {KiCad 8.0.5} date 2025-01-25T11:08:50+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-25T11:08:50+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X7.903Y-4.2981
X7.903Y-4.5659
T2
X7.279Y-3.519
X7.279Y-5.275
M30
